# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  AZURE_FUNCTIONAPP_NAME: 'senaclabazurefunctionjoliveiraa'   # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'       # set this to the path to your function app project, defaults to the repository root
  
permissions:
  id-token: write
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.7"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    # Executa os testes com Pytest e gera um relatório
    - name: Run tests with pytest
      run: |
          pytest > pytest-report.txt || true

    # Publish artifact
    - name: Create artifact
      uses: actions/upload-artifact@v3
      with:
        name: python-publish-app-artifact
        path: ./
   #Deploy steps
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: '475e21a0-ecbe-4592-a5c1-6ec9c0032773'       #${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: '6f9e3b1e-1809-444a-81d3-82d40a928812'       #${{ secrets.AZURE_TENANT_ID }}
        subscription-id: '28deb0ad-13a4-4cc4-bc84-200e87e44077' #${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true
          
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3 #ou @v3 v4.1.8
      with:
        name: python-publish-app-artifact
        path: ./artifact
        
    - name: Run Azure Functions Action
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }} # Remove publish-profile to use Azure RBAC
        scm-do-build-during-deployment: true
        enable-oryx-build: true
